sudo: required
dist: trusty

service:
  - docker

script:
  - chmod +x QtNaCl.sh
  - mkdir dockerBuild
  - cd dockerBuild
  - docker build -t qt_nacl ..
  - mkdir ../scriptBuild
  - cd ../scriptBuild
  - ../QtNaCl.sh > scipt.log

notifications:
  email: false